name: "Enforce JIRA Link"
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-title:
    runs-on: ubuntu-runners
    steps:
    - name: Check PR body
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
        script: |
          const payload = context.payload
          const prDesc = payload.pull_request.body
          // The pattern for JIRA ticket format
          const jiraPattern = /[A-Z]+-\d+/g
          if (!jiraPattern.test(prDesc)) {
            console.log('The PR description does not match JIRA ticket format!')
            // Fails the workflow
            core.setFailed('PR description does not match JIRA ticket format!')
          } else {
            console.log('PR description format is correct.')
          }
